config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'dashboards#index'

  resources :users

  resources :teams do
    scope module: :teams do
      resources :players
      resources :games
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  belongs_to :team
end

app/models/league.rb
# frozen_string_literal: true

class League < ApplicationRecord; end

app/models/league_session.rb
# frozen_string_literal: true

class LeagueSession < ApplicationRecord; end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord; end

app/models/player_game.rb
# frozen_string_literal: true

class PlayerGame < ApplicationRecord
  belongs_to :game
  belongs_to :team
  belongs_to :user
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :games, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  belongs_to :team, optional: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  def index; end
end

app/controllers/teams/games_controller.rb
# frozen_string_literal: true

module Teams
  class GamesController < ApplicationController
    before_action :set_team

    def index
      @games = Game.all
    end

    def show
      @game = Game.find(params[:id])
      @players = PlayerGame.where(game: @game)
    end

    def new; end

    def create; end

    def update; end

    def destroy; end

    private

    def set_team
      @team = Team.find(params[:team_id])
    end
  end
end

app/controllers/teams/players_controller.rb
# frozen_string_literal: true

module Teams
  class PlayersController < ApplicationController
    before_action :set_team, only: %i[create update destroy]

    def index
      render :new
    end

    def new
      @player = User.new
    end

    def create
      @player = User.new(player_params)
      @player.transaction do
        @player.team = @team
        @player.validate!
        @player.save!
      end
      redirect_to team_path(@team)
    end

    def update; end

    def destroy; end

    private

    def player_params
      params.permit(:first_name, :last_name, :phone_number, :email)
    end

    def set_team
      @team = Team.find(params[:team_id])
    end
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  before_action :set_team, only: %i[show]
  def index
    @teams = Team.all
  end

  def show
    @players = User.where(team_id: params[:id])
    @games = @team.games.order(:game_date_time)
  end

  def set_team
    @team = Team.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit show update destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit; end

  def show
    @full_name = "#{@user.first_name} #{@user.last_name}"
    @games = PlayerGame.where(user: @user)
  end

  def create
    @user = User.new(user_params)

    @user.transaction do
      @user.validate!
      @user.save!
    end
    redirect_to users_path
  rescue ActiveRecord::RecordInvalid
    render :new, status: :unprocessable_entity
  end

  def update
    @user.update(user_params)

    @user.transaction do
      @user.save!
    end
    redirect_to user_path(@user)
  rescue ActiveRecord::RecordInvalid
    render :update, status: :unprocessable_entity
  end

  def destroy
    @user.destroy!

    redirect_to users_path, notice: t('.destroy')
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :birthday)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
end

app/helpers/teams_helper.rb
# frozen_string_literal: true

module TeamsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/dashboards/index.html.erb
<%= link_to 'Users', users_path %>
<%= link_to 'Teams', teams_path %>

app/views/layouts/_header.html.erb
<h1 class="m-5 text-center">Welcome aboard Captn!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaptnClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
<div class="w-25 m-auto">
  <div class="d-flex justify-content-between mb-2">
    <%= f.label :first_name, class: 'form-label' %>
    <%= f.text_field :first_name, class: 'form-input' %>
  </div>
  <div class="d-flex justify-content-between mb-2">
    <%= f.label :last_name, class: 'form-label' %>
    <%= f.text_field :last_name, class: 'form-input' %>
  </div>
  <div class="d-flex justify-content-between mb-2">
    <%= f.label :birthday, class: 'form-label' %>
    <%= f.date_field :birthday, class: 'form-input' %>
  </div>
  <div class="d-flex justify-content-between mb-2">
    <%= f.label :phone_number, class: 'form-label' %>
    <%= f.number_field :phone_number, class: 'form-input' %>
  </div>
  <div class="d-flex justify-content-between mb-2">
    <%= f.label :email, class: 'form-label' %>
    <%= f.email_field :email, class: 'form-input' %>
  </div>
  <%= f.submit "Let's play!" %>
</div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<%= link_to 'Join Captn!', new_user_path %>

<% if @users.any? %>
  <% @users.each do |user| %>
    <%= link_to user.first_name, user_path(user) %>
  <% end %>
<% else %>
  <h3>No current users!</h3>
<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user, url: new_user_path %>

app/views/users/show.html.erb
<h1 class="text-center">Welcome <%= @full_name %>!</h1>

<div class="m-auto col-2">
  <h3 class="text-center mt-5 d-inline-block">Your information</h3>
  <%= link_to 'Edit', edit_user_path %>
</div>

<div class="card m-auto col-2">
  <div class="card-body">
    <p class="d-block"><i class="bi bi-envelope me-2"></i><%= @user.email %></p>
    <p class="d-block"><i class="bi bi-telephone me-2"></i><%= @user.phone_number %></p>
    <p class="d-block"><i class="bi bi-calendar-event me-2"></i><%= @user.birthday %></p>
  </div>
</div>

<div>
  <div class="card col-2 ms-5 d-inline-block">
    <div class="card-body">
      <h5>Games</h5>
      <div>
        <% @games.each do |game| %>
          <div class="card-body border">
            <p>Team: <%= game.team.name %></p>
            <p>Location: <%= game.game.location %></p>
            <p>When: <%= game.game.game_date_time.to_fs(:short) %></p>
            <p>Sport: <%= game.game.sport %></p>
            <p>Final score: <%= game.game.home_team_score %> - <%= game.game.away_team_score %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<%= button_to "Delete User", user_path(@user), method: :delete %>